FROM jenkins/jenkins:lts-jdk17
USER root

# Устанавливаем docker-compose
RUN apt-get update && apt-get install -y docker-compose

# Создаем группу docker (если нет) и добавляем jenkins в docker и root
RUN groupadd -f docker && \
    usermod -aG docker jenkins && \
    usermod -aG root jenkins

USER jenkins