version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    networks:
      - qa_network

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure
    ports:
      - "5050:5050"
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=1
      - KEEP_HISTORY=1
    volumes:
      - ./target/allure-results:/app/allure-results
    networks:
      - qa_network

  # Сервис для запуска тестов
  api-tests:
    build: .
    image: my-rest-assured-tests
    volumes:
      - .:/app                    # Монтируем код
      - ~/.m2:/root/.m2           # Монтируем кэш Maven
    networks:
      - qa_network
    profiles: ["test"]            # Не запускается автоматически

volumes:
  jenkins_home:

networks:
  qa_network:
    driver: bridge