FROM jenkins/jenkins:lts-jdk17

USER root

# Установка Docker
RUN apt-get update && \
    apt-get install -y docker.io docker-compose && \
    apt-get clean

# Даем доступ Jenkins к Docker
RUN groupadd -f docker && \
    usermod -aG docker jenkins

USER jenkins